site_name: zensus2pgsql
site_description:  A CLI program for importing geographic German census data into PostgreSQL 
site_url: https://travishathaway.github.io/zensus2pgsql
repo_url: https://github.com/travishathaway/zensus2pgsql
repo_name: travishathaway/zensus2pgsql

theme:
  name: material
  logo: assets/zensus2pgsql-logo-no-text-simple.svg
  favicon: assets/favicon.ico
  palette:
    primary: black

nav:
  - Start: index.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
